register:
  path: /register
  controller: App\Controller\AuthController::register
  methods: POST

emailConfirmation:
  path: /confirmation/{token}
  controller: App\Controller\AuthController::confirmEmail
  methods: [GET]

login_check:
  path: /api/login_check
  methods: [POST]