register:
  path: /register
  controller: App\Controller\AuthController::register
  methods: POST

emailConfirmation:
  path: /confirmation/{token}
  controller: App\Controller\AuthController::confirmEmail
  methods: [GET]

login_check:
  path: /api/login_check
  methods: [POST]

profile:
  path: /api/auth/profile
  methods: GET
  controller: App\Controller\AuthController::profile

myEvents:
  path: /api/auth/events
  methods: GET
  controller: App\Controller\EventController::myEvents

createEvent:
  path: /api/auth/events
  methods: POST
  controller: App\Controller\EventController::createEvent

getEvent:
  path: /api/auth/events/{event}
  methods: GET
  controller: App\Controller\EventController::getEvent

getPublicEvent:
  path: /api/auth/events/public/{publicId}
  methods: GET
  controller: App\Controller\EventController::getPublicEvent

editEvent:
  path: /api/auth/events
  methods: PUT
  controller: App\Controller\EventController::editEvent

deleteEvent:
  path: /api/auth/events/{event}
  methods: DELETE
  controller: App\Controller\EventController::deleteEvent
  requirements:
    event: '\d+'

editProfile:
  path: /api/auth/profile
  methods: PUT
  controller: App\Controller\AuthController::editProfile

changePassword:
  path: /api/auth/password
  methods: PUT
  controller: App\Controller\AuthController::changePassword